# ---------------------------------------------------------------------------
#
#         Developed by OPmasterLEO
#
#         https://github.com/Kaleshnikk
#         https://builtbybit.com/resources/moderncombat.65133/
#
# ---------------------------------------------------------------------------

# Version of the plugin that generated this configuration
generated-by-version: "v${project.version}" # DO NOT CHANGE
 
# Notify opped players about updates when they join the server
update-notify-chat: false

# Duration of the combat timer in seconds
Duration: 15

# Enable combat globally
combat-enabled: true

# Enable combat only in specific worlds | HIGHLY EXPERIMENTAL
# This feature is not fully tested and may cause issues.
# Use at your own risk!
# If you want to enable this feature, set 'enabled' to true and specify the worlds.
EnabledWorlds:
  enabled: false
  worlds:
    - world1
    - world2

Messages:
  Prefix: '' # Prefix for all messages
  NowInCombat: '' # empty = disabled
  NoLongerInCombat: '' # empty = disabled
  LogoutInCombat: '' # empty = disabled
  ElytraDisabled: '&cElytra usage is disabled while in combat.' # <--- add this line

# Enable custom death messages
# This feature does not modify vanilla death messages.
# It only adds a prefix to the death message.
CustomDeathMessage:
  enabled: false
  prefix: '&c☠ '  

# Disable Combat for all with OP permissions
ignore-op: false

# Disable Elytra in combat
disable-elytra: false

# Settings for the action bar message during combat
ActionBar:
  Enabled: true # Enables the action bar message
  Format: '&#C7CEDCCombat: &#37bff9%seconds%s'

# Combat Tag Glowing visual indicator
CombatTagGlowing:
  Enabled: true

Commands:
  Blocked: # List of commands that are blocked during combat
    - spawn
    - tpa
    - tpahere
    - home
    - homes
    - rtp
    - afk 
    - warp
    - warps
  Format: '&7You cannot use &c%command% &7while in combat!'

EnderPearl:
  Enabled: false # Enables restrictions on ender pearl usage during combat
  Distance: 25 # Maximum allowed teleport distance with ender pearls
  Format: '&cYou cannot teleport that far away in combat!'

# MasterCombat can link pets, such as wolves, cats, and other animals that can be tamed, to their owner.
# This will only link the attacker, not the entity that was attacked.
# Default: true
link-pets: true

# MasterCombat can link projectiles, such as arrows from skeletons, to their shooter.
# This will only link the attacker, not the entity that was attacked.
# Default: true
link-projectiles: true

# Which projectiles will be ignored when the 'link-projectiles' option is enabled?
# If 'link-projectiles' is false, all projectiles will be ignored.
# You can find a list of valid projectile types on the Spigot javadocs:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
ignored-projectiles:
  - EGG
  - ENDER_PEARL
  - SNOWBALL

# MasterCombat can link a fishing rod to the entity that cast it.
# This will only link the attacker, not the entity that was attacked.
# Default: true
# EXPERIMENTAL: This feature currently does not work as expected.
link-fishing-rod: true

# MasterCombat can sometimes link TNT to the entity that caused it to explode.
# This will only link the attacker, not the entity that was attacked.
# Default: true
link-tnt: true

# MasterCombat can link end crystals to their placer.
# This will only link the attacker, not the entity that was attacked.
# Default: true
link-end-crystals: true

# Should MasterCombat tag players when they shoot themselves with a projectile?
# Default: false
self-combat: false

# Should MasterCombat remove players from combat when they are killed?
# Default: true
untag-on-death: true

# Should MasterCombat remove players from combat when their enemy is killed?
# This also removed combat if the enemy is a creeper and decides to explode.
# Default: true
untag-on-enemy-death: true

# Cooldown for movement checks in milliseconds
movement-cooldown: 200

# Timeout for update confirmation in milliseconds
update-confirmation-timeout: 10000

# Interval for update checks in minutes
update-check-interval: 120

# Anti-Cheat Integration: disables speed/fly effects while in combat
AntiCheatIntegration: true
