name: ${project.name}
main: net.opmasterleo.mastersmpcore.main
version: ${project.version}
description: ${project.description}
author: ${project.author}
folia-supported: true
api-version: 1.21
depend: [WorldGuard]
softdepend: [LuckPerms]

commands:
  findplayer:
    description: Find the world of a specified player.
    usage: /findplayer <player>
  ping:
    description: Check your ping or another player's ping.
    usage: /ping [player]
  mastercorereload:
    description: Reload the plugin configuration.
    usage: /mastercorereload
  subscription:
    description: Manage player subscriptions.
    usage: /subscription add <user> <luckperms_rank> <duration>
  fly:
    description: Toggle flight mode.
    usage: /fly
  silentgive:
    description: Silently give an item to a player.
    usage: /silentgive <player> <item> <amount>
    permission: mastersmp.silentgive

permissions:
  mastersmp.findplayer:
    description: Allows the use of the /findplayer command.
    default: true
  mastersmp.ping:
    description: Allows the use of the /ping command.
    default: true
  mastersmp.mastercorereload:
    description: Allows the use of the /mastercorereload command.
    default: op
  mastersmp.fly.use:
    description: Allows the use of the fly feature in specific worlds.
    default: false
  mastersmp.fly.command:
    description: Allows the use of the /fly command.
    default: op
  mastersmp.silentgive:
    description: Allows the use of the /silentgive command.
    default: op